DROP TABLE IF EXISTS DEV.DISTRITO;
GO
DROP TABLE IF EXISTS DEV.PROVINCIA;
GO
DROP TABLE IF EXISTS DEV.DEPARTAMENTO;
GO
DROP TABLE IF EXISTS DEV.USUARIO;
GO
DROP TABLE IF EXISTS DEV.TRABAJADOR;
GO
DROP TABLE IF EXISTS DEV.SUCURSAL;
GO
DROP TABLE IF EXISTS DEV.EMPRESA
GO