DROP TABLE DEV.USUARIO;
DROP TABLE DEV.TRABAJADOR;
DROP TABLE DEV.SUCURSAL;
DROP TABLE DEV.EMPRESA


CREATE TABLE DEV.EMPRESA 
(
	empr_Id INTEGER NOT NULL IDENTITY(1,1),
	empr_RazonSocial VARCHAR(200) NOT NULL,
	empr_NroDocumento VARCHAR(11) NOT NULL,
	empr_Logo VARCHAR(200) NOT NULL
);
GO
ALTER TABLE DEV.EMPRESA ADD CONSTRAINT pk_empresa PRIMARY KEY (empr_Id)
GO
CREATE TABLE DEV.SUCURSAL
(
	sucu_Id INTEGER NOT NULL IDENTITY(1,1),
	empr_Id INTEGER NOT NULL,
	sucu_Direccion VARCHAR(300) NOT NULL,
	sucu_CodSunat VARCHAR(10) NOT NULL
);
GO
ALTER TABLE DEV.SUCURSAL ADD CONSTRAINT pk_sucursal PRIMARY KEY (sucu_Id);
GO
ALTER TABLE DEV.SUCURSAL ADD CONSTRAINT fk_sucursal_empresa FOREIGN KEY (empr_Id) REFERENCES DEV.EMPRESA(empr_Id);
GO
CREATE TABLE DEV.TRABAJADOR
(
	trab_id INT NOT NULL IDENTITY(1,1),
	trab_TipoDocumento SMALLINT NOT NULL,
	trab_Documento VARCHAR(15) NOT NULL,
	trab_Nombres VARCHAR(50) NOT NULL,
	trab_ApellidoPaterno VARCHAR(20) NOT NULL,
	trab_ApellidoMaterno VARCHAR(20) NOT NULL,
	trab_EstadoCivil SMALLINT NOT NULL,
	trab_Estado INT NOT NULL,
	trab_Marcabaja INT NOT NULL,
	trab_FechaNacimiento DATE NOT NULL,
	trab_FechaRegistro DATETIME NOT NULL,
	trab_UsuarioRegistro VARCHAR(20) NOT NULL,
	trab_FechaModifica DATETIME NULL,
	trab_UsuarioModifica VARCHAR(20) NULL,
	empr_Id INTEGER NOT NULL
);
GO
ALTER TABLE DEV.TRABAJADOR ADD CONSTRAINT pk_trabajador PRIMARY KEY (trab_id);
GO
ALTER TABLE DEV.TRABAJADOR ADD CONSTRAINT fk_trabajador_empresa FOREIGN KEY (empr_Id) REFERENCES DEV.EMPRESA(empr_Id);
GO
CREATE TABLE DEV.USUARIO
(
	usua_Id INT NOT NULL IDENTITY(1,1),
	usua_Usuario VARCHAR(20) NOT NULL,
	usua_Password VARCHAR(100) NOT NULL,
	usua_Estado INT NOT NULL,
	usua_Marcabaja SMALLINT NOT NULL, 
	trab_Id INT NOT NULL,
	usua_FechaAlta DATE NOT NULL,
	usua_FechaRegistro DATE NOT NULL,
	usua_UsuarioRegistro VARCHAR(20) NOT NULL,
	usua_FechaModifica DATE NULL,
	usua_UsuarioModifica VARCHAR(20) NULL,
	sucu_Id INTEGER NOT NULL
);
GO

ALTER TABLE DEV.USUARIO ADD CONSTRAINT pk_usuario PRIMARY KEY (usua_Id);
GO
ALTER TABLE DEV.USUARIO ADD CONSTRAINT fk_usuario_trabajador FOREIGN KEY (trab_Id) REFERENCES DEV.TRABAJADOR(trab_Id);
GO
ALTER TABLE DEV.USUARIO ADD CONSTRAINT fk_usuario_sucursal FOREIGN KEY (sucu_Id) REFERENCES DEV.SUCURSAL(sucu_Id);
GO

