/*DROP TABLE DEV.USUARIO;
DROP TABLE DEV.TRABAJADOR;
DROP TABLE DEV.SUCURSAL;
DROP TABLE DEV.EMPRESA
*/
CREATE TABLE DEV.DEPARTAMENTO
(
	dept_Ubigeo CHAR(2) NOT NULL,
	dept_Descripcion VARCHAR(20) NOT NULL
);
GO
ALTER TABLE DEV.DEPARTAMENTO ADD CONSTRAINT pk_departamento PRIMARY KEY (dept_Ubigeo);
GO
CREATE TABLE DEV.PROVINCIA
(
	prov_Ubigeo CHAR(4) NOT NULL,
	prov_Descripcion VARCHAR(50) NOT NULL,
	dept_Ubigeo CHAR(2) NOT NULL
);
GO
ALTER TABLE DEV.PROVINCIA ADD CONSTRAINT pk_provincia PRIMARY KEY (prov_Ubigeo);
GO
ALTER TABLE DEV.PROVINCIA ADD CONSTRAINT fk_provincia_departamento FOREIGN KEY (dept_Ubigeo) REFERENCES DEV.DEPARTAMENTO (dept_Ubigeo);
GO
CREATE TABLE DEV.DISTRITO
(
	dist_Ubigeo CHAR(6) NOT NULL,
	dist_Descripcion VARCHAR(50) NOT NULL,
	prov_Ubigeo CHAR(4) NOT NULL
);
GO
ALTER TABLE DEV.DISTRITO ADD CONSTRAINT pk_distrito PRIMARY KEY (dist_Ubigeo);
GO
ALTER TABLE DEV.DISTRITO ADD CONSTRAINT fk_distrito_provincia FOREIGN KEY (prov_Ubigeo) REFERENCES DEV.PROVINCIA (prov_Ubigeo);
GO

CREATE SCHEMA DEV;
GO
CREATE TABLE DEV.EMPRESA 
(
	empr_Id INTEGER NOT NULL IDENTITY(1,1),
	empr_RazonSocial VARCHAR(200) NOT NULL,
	empr_NroDocumento VARCHAR(11) NOT NULL,
	empr_Logo VARCHAR(200) NOT NULL
);
GO
ALTER TABLE DEV.EMPRESA ADD CONSTRAINT pk_empresa PRIMARY KEY (empr_Id)
GO
CREATE TABLE DEV.SUCURSAL
(
	sucu_Id INTEGER NOT NULL IDENTITY(1,1),
	empr_Id INTEGER NOT NULL,
	sucu_Nombre VARCHAR(50) NOT NULL,
	sucu_Descripcion VARCHAR(300) NULL,
	sucu_Direccion VARCHAR(300) NOT NULL,
	sucu_CodSunat VARCHAR(10) NOT NULL
);
GO
ALTER TABLE DEV.SUCURSAL ADD CONSTRAINT pk_sucursal PRIMARY KEY (sucu_Id);
GO
ALTER TABLE DEV.SUCURSAL ADD CONSTRAINT fk_sucursal_empresa FOREIGN KEY (empr_Id) REFERENCES DEV.EMPRESA(empr_Id);
GO
CREATE TABLE DEV.TRABAJADOR
(
	trab_id INT NOT NULL IDENTITY(1,1),
	trab_TipoDocumento SMALLINT NOT NULL,
	trab_Documento VARCHAR(15) NOT NULL,
	trab_Nombres VARCHAR(50) NOT NULL,
	trab_ApellidoPaterno VARCHAR(20) NOT NULL,
	trab_ApellidoMaterno VARCHAR(20) NOT NULL,
	trab_EstadoCivil SMALLINT NOT NULL,
	trab_Estado INT NOT NULL,
	trab_Marcabaja INT NOT NULL,
	trab_FechaNacimiento DATE NOT NULL,
	trab_Sexo INT NOT NULL,
	trab_LugarNacimiento CHAR(6) NOT NULL,
	trab_FechaRegistro DATETIME NOT NULL,
	trab_UsuarioRegistro VARCHAR(20) NOT NULL,
	trab_FechaModifica DATETIME NULL,
	trab_UsuarioModifica VARCHAR(20) NULL,
	empr_Id INTEGER NOT NULL
);
GO
ALTER TABLE DEV.TRABAJADOR ADD CONSTRAINT pk_trabajador PRIMARY KEY (trab_id);
GO
ALTER TABLE DEV.TRABAJADOR ADD CONSTRAINT fk_trabajador_empresa FOREIGN KEY (empr_Id) REFERENCES DEV.EMPRESA(empr_Id);
GO
CREATE TABLE DEV.CORREO
(
	corr_Id INT IDENTITY(1,1) NOT NULL,
	trab_Id INT NULL,
	corr_Correo VARCHAR(200) NOT NULL
);
GO
ALTER TABLE DEV.CORREO ADD CONSTRAINT pk_correo PRIMARY KEY (corr_Id);
GO
ALTER TABLE DEV.CORREO ADD CONSTRAINT fk_correo_trabajador FOREIGN KEY (trab_Id) REFERENCES DEV.TRABAJADOR(trab_id);
GO
CREATE TABLE DEV.CELULAR
(
	celu_Id INT IDENTITY(1,1) NOT NULL,
	trab_Id INT NULL,
	celu_Celular VARCHAR(12) NOT NULL
);
GO
ALTER TABLE DEV.CELULAR ADD CONSTRAINT pk_celular PRIMARY KEY (celu_Id);
GO
ALTER TABLE DEV.CELULAR ADD CONSTRAINT fk_celular_trabajador FOREIGN KEY (trab_Id) REFERENCES DEV.TRABAJADOR(trab_id);
GO
CREATE TABLE DEV.TELEFONO
(
	telf_Id INT IDENTITY(1,1) NOT NULL,
	trab_Id INT NULL,
	telf_Telefono VARCHAR(12) NOT NULL
);
GO
ALTER TABLE DEV.TELEFONO ADD CONSTRAINT pk_telefono PRIMARY KEY (telf_Id);
GO
ALTER TABLE DEV.TELEFONO ADD CONSTRAINT fk_telefono_trabajador FOREIGN KEY (trab_Id) REFERENCES DEV.TRABAJADOR(trab_id);
GO
CREATE TABLE DEV.DIRECCION
(
	dire_Id INT IDENTITY(1,1) NOT NULL,
	trab_Id INT NULL,
	dire_Direccion VARCHAR(12) NOT NULL
);
GO
ALTER TABLE DEV.DIRECCION ADD CONSTRAINT pk_telefono PRIMARY KEY (dire_Id);
GO
ALTER TABLE DEV.DIRECCION ADD CONSTRAINT fk_direccion_trabajador FOREIGN KEY (trab_Id) REFERENCES DEV.TRABAJADOR(trab_id);
GO
CREATE TABLE DEV.USUARIO
(
	usua_Id INT NOT NULL IDENTITY(1,1),
	usua_Usuario VARCHAR(20) NOT NULL,
	usua_Password VARBINARY(8000) NOT NULL,
	usua_Estado INT NOT NULL,
	usua_Marcabaja SMALLINT NOT NULL, 
	trab_Id INT NOT NULL,
	usua_FechaAlta DATE NOT NULL,
	usua_FechaRegistro DATE NOT NULL,
	usua_UsuarioRegistro VARCHAR(20) NOT NULL,
	usua_FechaModifica DATE NULL,
	usua_UsuarioModifica VARCHAR(20) NULL,
	sucu_Id INTEGER NOT NULL
);
GO

ALTER TABLE DEV.USUARIO ADD CONSTRAINT pk_usuario PRIMARY KEY (usua_Id);
GO
ALTER TABLE DEV.USUARIO ADD CONSTRAINT fk_usuario_trabajador FOREIGN KEY (trab_Id) REFERENCES DEV.TRABAJADOR(trab_Id);
GO
ALTER TABLE DEV.USUARIO ADD CONSTRAINT fk_usuario_sucursal FOREIGN KEY (sucu_Id) REFERENCES DEV.SUCURSAL(sucu_Id);
GO

CREATE TABLE DEV.PERFIL
(
	perf_Id INTEGER IDENTITY(1,1) NOT NULL,
	perf_Nombre VARCHAR(50) NOT NULL,
	perf_Estado INT NOT NULL,
	perf_Marcabaja SMALLINT NOT NULL,
	empr_Id INT NOT NULL,
	perf_FechaRegistro DATE NOT NULL,
	perf_UsuarioRegistro VARCHAR(20) NOT NULL,
	perf_FechaModifica DATE NULL,
	perf_UsuarioModifica VARCHAR(20)
);
GO
ALTER TABLE DEV.PERFIL ADD CONSTRAINT pk_perfil PRIMARY KEY (perf_Id);
GO
ALTER TABLE DEV.PERFIL ADD CONSTRAINT fk_perfil_empresa FOREIGN KEY (empr_Id) REFERENCES DEV.EMPRESA(empr_Id);
GO
CREATE TABLE DEV.PERMISO
(
	perm_Id INTEGER IDENTITY(1,1) NOT NULL,
	perm_Titulo VARCHAR(50) NOT NULL,
	perm_Formulario VARCHAR(50) NOT NULL,
	perm_Icono VARCHAR(200) NOT NULL,
	perm_FechaRegistro DATE NOT NULL,
	perm_UsuarioRegistro VARCHAR(20) NOT NULL,
	perm_FechaModifica DATE NULL,
	perm_UsuarioModifica VARCHAR(20) NULL,
	empr_Id INTEGER NOT NULL
);
GO
ALTER TABLE DEV.PERMISO ADD CONSTRAINT pk_permiso PRIMARY KEY (perm_Id);
GO
ALTER TABLE DEV.PERMISO ADD CONSTRAINT fk_permiso_perfil FOREIGN KEY (empr_Id) REFERENCES DEV.EMPRESA(empr_Id);
GO
CREATE TABLE DEV.PERFIL_PERMISO
(
	perm_Id INTEGER NOT NULL,
	perf_Id INTEGER NOT NULL,
	rela_FechaRegistro DATE NOT NULL,
	rela_UsuarioRegistro VARCHAR(20) NOT NULL,
	rela_FechaModifica DATE NULL,
	rela_UsuarioModifica VARCHAR(20) NULL
);
GO
ALTER TABLE DEV.PERFIL_PERMISO ADD CONSTRAINT pk_perfil_permiso PRIMARY KEY (perm_Id, perf_Id);
GO

CREATE TABLE DEV.PERFIL_USUARIO
(
	perf_Id INTEGER NOT NULL,
	usua_Id INTEGER NOT NULL,
	rela_FechaRegistro DATE NOT NULL,
	rela_UsuarioRegistro VARCHAR(20) NOT NULL,
	rela_FechaModifica DATE NULL,
	rela_UsuarioModifica VARCHAR(20) NULL
);
GO
ALTER TABLE DEV.PERFIL_USUARIO ADD CONSTRAINT pk_perfil_usuario PRIMARY KEY (perf_Id, usua_Id);
GO

CREATE TABLE DEV.CONTROL_ERROR
(
	cerr_Id BIGINT IDENTITY(1,1) NOT NULL,
	cerr_Formulario VARCHAR(50) NOT NULL,
	cerr_MensajeError VARCHAR(500) NOT NULL,
	cerr_Traza VARCHAR(5000) NOT NULL,
	cerr_Usuario VARCHAR(20) NOT NULL,
	cerr_Trama VARCHAR(5000) NOT NULL,
	cerr_FechaError DATE NOT NULL
);
GO
ALTER TABLE DEV.CONTROL_ERROR ADD CONSTRAINT pk_control_error PRIMARY KEY (cerr_Id);
GO

CREATE TABLE DEV.CONCEPTO
(
	conc_Prefijo INTEGER NOT NULL,
	conc_Correlativo INTEGER NOT NULL,
	conc_Descripcion VARCHAR(100) NOT NULL,
	conc_Abreviatura VARCHAR(5) NOT NULL
);
GO
ALTER TABLE DEV.CONCEPTO ADD CONSTRAINT pk_concepto PRIMARY KEY (conc_Prefijo, conc_Correlativo);
GO


